In [17]:
import pandas as pd
import plotly.express as px

df = pd.read_csv('googleplaystore.csv')
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [18]:
df.tail()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [19]:
df.sample(5)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
8418,DEER HUNTER CHALLENGE,GAME,3.7,38767,4.1M,"5,000,000+",Free,0,Everyone 10+,Action,"April 11, 2011",1.4.3,2.0 and up
4442,Verdad o Reto,SOCIAL,3.8,826,5.1M,"500,000+",Free,0,Teen,Social,"May 10, 2018",2.0,4.1 and up
9846,Beauty and the Beast,FAMILY,4.4,70883,31M,"1,000,000+",Free,0,Everyone,Puzzle;Creativity,"August 7, 2018",1.7.6,4.2 and up
1185,Frigo Magic: Easy recipe idea and anti-waste,FOOD_AND_DRINK,4.1,2473,14M,"500,000+",Free,0,Everyone,Food & Drink,"July 28, 2018",3.1.5,4.4 and up
425,Lightning Web Browser,COMMUNICATION,4.1,12578,2.3M,"500,000+",Free,0,Everyone,Communication,"July 10, 2017",4.5.1,4.0 and up

In [20]:
df.Category.unique()

array(['ART_AND_DESIGN', 'AUTO_AND_VEHICLES', 'BEAUTY',
       'BOOKS_AND_REFERENCE', 'BUSINESS', 'COMICS', 'COMMUNICATION',
       'DATING', 'EDUCATION', 'ENTERTAINMENT', 'EVENTS', 'FINANCE',
       'FOOD_AND_DRINK', 'HEALTH_AND_FITNESS', 'HOUSE_AND_HOME',
       'LIBRARIES_AND_DEMO', 'LIFESTYLE', 'GAME', 'FAMILY', 'MEDICAL',
       'SOCIAL', 'SHOPPING', 'PHOTOGRAPHY', 'SPORTS', 'TRAVEL_AND_LOCAL',
       'TOOLS', 'PERSONALIZATION', 'PRODUCTIVITY', 'PARENTING', 'WEATHER',
       'VIDEO_PLAYERS', 'NEWS_AND_MAGAZINES', 'MAPS_AND_NAVIGATION',
       '1.9'], dtype=object)

In [21]:
df.Category.nunique()

34

In [22]:
df.Category.value_counts()

FAMILY                 1972
GAME                   1144
TOOLS                   843
MEDICAL                 463
BUSINESS                460
PRODUCTIVITY            424
PERSONALIZATION         392
COMMUNICATION           387
SPORTS                  384
LIFESTYLE               382
FINANCE                 366
HEALTH_AND_FITNESS      341
PHOTOGRAPHY             335
SOCIAL                  295
NEWS_AND_MAGAZINES      283
SHOPPING                260
TRAVEL_AND_LOCAL        258
DATING                  234
BOOKS_AND_REFERENCE     231
VIDEO_PLAYERS           175
EDUCATION               156
ENTERTAINMENT           149
MAPS_AND_NAVIGATION     137
FOOD_AND_DRINK          127
HOUSE_AND_HOME           88
LIBRARIES_AND_DEMO       85
AUTO_AND_VEHICLES        85
WEATHER                  82
ART_AND_DESIGN           65
EVENTS                   64
PARENTING                60
COMICS                   60
BEAUTY                   53
1.9                       1
Name: Category, dtype: int64

In [23]:
df.Category.value_counts(normalize=True)

FAMILY                 0.181902
GAME                   0.105525
TOOLS                  0.077760
MEDICAL                0.042708
BUSINESS               0.042432
PRODUCTIVITY           0.039111
PERSONALIZATION        0.036159
COMMUNICATION          0.035698
SPORTS                 0.035421
LIFESTYLE              0.035237
FINANCE                0.033761
HEALTH_AND_FITNESS     0.031455
PHOTOGRAPHY            0.030901
SOCIAL                 0.027212
NEWS_AND_MAGAZINES     0.026105
SHOPPING               0.023983
TRAVEL_AND_LOCAL       0.023799
DATING                 0.021585
BOOKS_AND_REFERENCE    0.021308
VIDEO_PLAYERS          0.016142
EDUCATION              0.014390
ENTERTAINMENT          0.013744
MAPS_AND_NAVIGATION    0.012637
FOOD_AND_DRINK         0.011715
HOUSE_AND_HOME         0.008117
LIBRARIES_AND_DEMO     0.007841
AUTO_AND_VEHICLES      0.007841
WEATHER                0.007564
ART_AND_DESIGN         0.005996
EVENTS                 0.005904
PARENTING              0.005535
COMICS                 0.005535
BEAUTY                 0.004889
1.9                    0.000092
Name: Category, dtype: float64

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10840 non-null  object
 9   Genres          10841 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10838 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB

In [25]:
df.describe()

            Rating
count  9367.000000
mean      4.193338
std       0.537431
min       1.000000
25%       4.000000
50%       4.300000
75%       4.500000
max      19.000000

In [26]:
# Pandas Profiling
# from ydata_profiling import ProfileReport
# profile = ProfileReport(df, title='Pandas Profiling Report', html={'style':{'full_width':True}})
# profile.to_file(output_file="playstore.html")

In [27]:
%%writefile my_analysis.py

import pandas as pd
import plotly.express as px

def univariate_numerical(df, col):
    print(df.describe())
    fig = px.histogram(df, x=col, title=col)
    fig.show()
    fig2 = px.box(df, x=col, title=col)
    fig2.show()

def univariate_categorical(df, col):
    print(df[col].value_counts())
    print(df[col].nunique())
    fig = px.bar(df[col].value_counts(), title=col)
    fig.show()

Overwriting my_analysis.py

In [28]:
import my_analysis

my_analysis.univariate_numerical(df, 'Rating')

            Rating
count  9367.000000
mean      4.193338
std       0.537431
min       1.000000
25%       4.000000
50%       4.300000
75%       4.500000
max      19.000000

In [29]:
def univariate_numerical(df, col):
    print(df.describe())
    fig = px.histogram(df, x=col, title=col)
    fig.show()
    fig2 = px.box(df, x=col, title=col)
    fig2.show()

def univariate_categorical(df, col):
    print(df[col].value_counts())
    print(df[col].nunique())
    fig = px.bar(df[col].value_counts(), title=col)
    fig.show()

In [30]:
numerical_cols = df.select_dtypes(exclude='object').columns
categorical_cols = df.select_dtypes(include='object').columns

In [31]:
for cat_col in categorical_cols:
    print(cat_col)
    univariate_categorical(df, cat_col)
    print('-------------------')

App
ROBLOX                                                9
CBS Sports App - Scores, News, Stats & Watch Live     8
ESPN                                                  7
Duolingo: Learn Languages Free                        7
Candy Crush Saga                                      7
                                                     ..
Meet U - Get Friends for Snapchat, Kik & Instagram    1
U-Report                                              1
U of I Community Credit Union                         1
Waiting For U Launcher Theme                          1
iHoroscope - 2018 Daily Horoscope & Astrology         1
Name: App, Length: 9660, dtype: int64
9660

-------------------
Category
FAMILY                 1972
GAME                   1144
TOOLS                   843
MEDICAL                 463
BUSINESS                460
PRODUCTIVITY            424
PERSONALIZATION         392
COMMUNICATION           387
SPORTS                  384
LIFESTYLE               382
FINANCE                 366
HEALTH_AND_FITNESS      341
PHOTOGRAPHY             335
SOCIAL                  295
NEWS_AND_MAGAZINES      283
SHOPPING                260
TRAVEL_AND_LOCAL        258
DATING                  234
BOOKS_AND_REFERENCE     231
VIDEO_PLAYERS           175
EDUCATION               156
ENTERTAINMENT           149
MAPS_AND_NAVIGATION     137
FOOD_AND_DRINK          127
HOUSE_AND_HOME           88
LIBRARIES_AND_DEMO       85
AUTO_AND_VEHICLES        85
WEATHER                  82
ART_AND_DESIGN           65
EVENTS                   64
PARENTING                60
COMICS                   60
BEAUTY                   53
1.9                       1
Name: Category, dtype: int64
34

-------------------
Reviews
0         596
1         272
2         214
3         175
4         137
         ...
342912      1
4272        1
5517        1
4057        1
398307      1
Name: Reviews, Length: 6002, dtype: int64
6002

-------------------
Size
Varies with device    1695
11M                    198
12M                    196
14M                    194
13M                    191
                      ...
429k                     1
200k                     1
460k                     1
728k                     1
619k                     1
Name: Size, Length: 462, dtype: int64
462

-------------------
Installs
1,000,000+        1579
10,000,000+       1252
100,000+          1169
10,000+           1054
1,000+             907
5,000,000+         752
100+               719
500,000+           539
50,000+            479
5,000+             477
100,000,000+       409
10+                386
500+               330
50,000,000+        289
50+                205
5+                  82
500,000,000+        72
1+                  67
1,000,000,000+      58
0+                  14
0                    1
Free                 1
Name: Installs, dtype: int64
22

-------------------
Type
Free    10039
Paid      800
0           1
Name: Type, dtype: int64
3

-------------------
Price
0         10040
$0.99       148
$2.99       129
$1.99        73
$4.99        72
          ...
$1.75         1
$14.00        1
$4.85         1
$46.99        1
$1.04         1
Name: Price, Length: 93, dtype: int64
93

-------------------
Content Rating
Everyone           8714
Teen               1208
Mature 17+          499
Everyone 10+        414
Adults only 18+       3
Unrated               2
Name: Content Rating, dtype: int64
6

-------------------
Genres
Tools                     842
Entertainment             623
Education                 549
Medical                   463
Business                  460
                         ...
Arcade;Pretend Play         1
Card;Brain Games            1
Lifestyle;Pretend Play      1
Comics;Creativity           1
Strategy;Creativity         1
Name: Genres, Length: 120, dtype: int64
120

-------------------
Last Updated
August 3, 2018        326
August 2, 2018        304
July 31, 2018         294
August 1, 2018        285
July 30, 2018         211
                     ...
March 20, 2014          1
April 7, 2015           1
September 22, 2014      1
October 3, 2015         1
March 23, 2014          1
Name: Last Updated, Length: 1378, dtype: int64
1378

-------------------
Current Ver
Varies with device    1459
1.0                    809
1.1                    264
1.2                    178
2.0                    151
                      ...
1.0.17.3905              1
15.1.2                   1
4.94.19                  1
1.1.11.11                1
2.0.148.0                1
Name: Current Ver, Length: 2832, dtype: int64
2832

-------------------
Android Ver
4.1 and up            2451
4.0.3 and up          1501
4.0 and up            1375
Varies with device    1362
4.4 and up             980
2.3 and up             652
5.0 and up             601
4.2 and up             394
2.3.3 and up           281
2.2 and up             244
4.3 and up             243
3.0 and up             241
2.1 and up             134
1.6 and up             116
6.0 and up              60
7.0 and up              42
3.2 and up              36
2.0 and up              32
5.1 and up              24
1.5 and up              20
4.4W and up             12
3.1 and up              10
2.0.1 and up             7
8.0 and up               6
7.1 and up               3
4.0.3 - 7.1.1            2
5.0 - 8.0                2
1.0 and up               2
7.0 - 7.1.1              1
4.1 - 7.1.1              1
5.0 - 6.0                1
2.2 - 7.1.1              1
5.0 - 7.1.1              1
Name: Android Ver, dtype: int64
33

-------------------

In [32]:
for num_col in numerical_cols:
    print(num_col)
    univariate_numerical(df, num_col)
    print('-------------------')

Rating
            Rating
count  9367.000000
mean      4.193338
std       0.537431
min       1.000000
25%       4.000000
50%       4.300000
75%       4.500000
max      19.000000

-------------------

In [33]:
def bivariate_numerical(df, col1, col2):
    fig = px.scatter(df, x=col1, y=col2, title=f'{col1} vs {col2}')
    fig.show()

In [34]:
bivariate_numerical(df, 'Rating', 'Reviews')

In [35]:
# Drop duplicates
print ('Duplicate rows before: ', df.duplicated().sum())
df.drop_duplicates(subset='App', inplace=True)  
print ('Duplicate rows after: ', df.duplicated().sum())

Duplicate rows before:  483
Duplicate rows after:  0

In [36]:
# Missing values Percentage
print ('Missing values percentage:\n', df.isnull().mean()*100)

Missing values percentage:
 App                0.000000
Category           0.000000
Rating            15.144928
Reviews            0.000000
Size               0.000000
Installs           0.000000
Type               0.010352
Price              0.000000
Content Rating     0.010352
Genres             0.000000
Last Updated       0.000000
Current Ver        0.082816
Android Ver        0.031056
dtype: float64

Since the one of the main targets to inspect is the rating, we will drop the rows with no rating.
Also, All remaining features with missing values have a small number of missing values, so we will drop the rows with missing values.

In [37]:
# Drop Missing values
print('Total Missing values before: ', df.isnull().sum().sum())
df.dropna(inplace=True)
print('Total Missing values after: ', df.isnull().sum().sum())

Total Missing values before:  1476
Total Missing values after:  0

In [38]:
# Category
print ('Unique Categories: ', df['Category'].nunique())

# Value counts of each category with percentage
print ('Value counts of each category with percentage:\n', df['Category'].value_counts(normalize=True)*100)

Unique Categories:  33
Value counts of each category with percentage:
 FAMILY                 19.621490
GAME                   11.135531
TOOLS                   8.754579
FINANCE                 3.687424
PRODUCTIVITY            3.675214
LIFESTYLE               3.675214
PERSONALIZATION         3.614164
MEDICAL                 3.540904
BUSINESS                3.211233
PHOTOGRAPHY             3.211233
SPORTS                  3.174603
COMMUNICATION           3.125763
HEALTH_AND_FITNESS      2.979243
NEWS_AND_MAGAZINES      2.490842
SOCIAL                  2.478632
TRAVEL_AND_LOCAL        2.283272
SHOPPING                2.197802
BOOKS_AND_REFERENCE     2.063492
VIDEO_PLAYERS           1.807082
DATING                  1.636142
MAPS_AND_NAVIGATION     1.440781
EDUCATION               1.440781
ENTERTAINMENT           1.245421
FOOD_AND_DRINK          1.147741
AUTO_AND_VEHICLES       0.891331
WEATHER                 0.879121
LIBRARIES_AND_DEMO      0.769231
HOUSE_AND_HOME          0.757021
ART_AND_DESIGN          0.732601
COMICS                  0.659341
PARENTING               0.610501
EVENTS                  0.549451
BEAUTY                  0.512821
Name: Category, dtype: float64

In [39]:
# Visualize the categorie
import plotly.express as px

# Sorted bar plot 
fig = px.bar(df['Category'].value_counts().sort_values(ascending=False),
                title='Category Count',
                labels={'value':'Count', 'index':'Category'})
fig.show()

In [40]:
# Sorted bar plot 
fig = px.bar(df['Category'].value_counts(normalize=True).sort_values(ascending=False)*100,
                title='Category Percentage',
                labels={'value':'Perentage', 'index':'Category'})
fig.show()

In [41]:
# Cumulative bar plot
fig = px.bar(df['Category'].value_counts(normalize=True).sort_values(ascending=False).cumsum()*100,
                title='Category Cumulative Percentage',
                labels={'value':'Perentage', 'index':'Category'})
fig.show()

In [42]:
# Top 10 categories
fig = px.bar(df['Category'].value_counts(normalize=True).sort_values(ascending=False)[:10]*100,
                title='Top 10 Category Percentage',
                labels={'value':'Perentage', 'index':'Category'}, width=800, height=500)
fig.update_layout(showlegend=False)
# Annotations with white font color
annotations = []
for i, v in enumerate(df['Category'].value_counts(normalize=True).sort_values(ascending=False)[:10]*100):
    annotations.append(dict(x=i, y=v-1, text=str(round(v))+'%', font_size=10, showarrow=False))
fig.update_layout(annotations=annotations)
fig.update_annotations(font_color='white')
fig.show()

In [43]:
# Bottom 10 categories
fig = px.bar(df['Category'].value_counts().sort_values(ascending=False)[-10:],
                title='Bottom 10 Category Count',
                labels={'value':'Count', 'index':'Category'}, width=800, height=500)
fig.update_layout(showlegend=False)
annotations = []
for i, v in enumerate(df['Category'].value_counts().sort_values(ascending=False)[-10:]):
    annotations.append(dict(x=i, y=v+3, text=str(round(v)), font_size=10, showarrow=False))
fig.update_layout(annotations=annotations)
fig.show()

In [44]:
# Genres
print ('Unique Genres: ', df['Genres'].nunique())

# Value counts of each Genres with percentage
print ('Value counts of each Genres with percentage:\n', df['Genres'].value_counts(normalize=True)*100)

Unique Genres:  114
Value counts of each Genres with percentage:
 Tools                          8.742369
Entertainment                  5.750916
Education                      5.238095
Finance                        3.687424
Productivity                   3.675214
                                 ...
Health & Fitness;Education     0.012210
Music & Audio;Music & Video    0.012210
Arcade;Pretend Play            0.012210
Art & Design;Pretend Play      0.012210
Strategy;Creativity            0.012210
Name: Genres, Length: 114, dtype: float64

In [45]:
# Art and Design
print ('Art and Design:\n', df[df['Category']=='ART_AND_DESIGN']['Genres'].value_counts(normalize=True)*100)

Art and Design:
 Art & Design                 90.000000
Art & Design;Creativity       8.333333
Art & Design;Pretend Play     1.666667
Name: Genres, dtype: float64

In [46]:
# Entertainment
print ('Entertainment:\n', df[df['Category']=='ENTERTAINMENT']['Genres'].value_counts(normalize=True)*100)

Entertainment:
 Entertainment                  90.196078
Entertainment;Music & Video     6.862745
Entertainment;Brain Games       1.960784
Entertainment;Creativity        0.980392
Name: Genres, dtype: float64

So, We will consider the category only for the analysis, so we will drop the genre column.

In [47]:
# Rating
px.histogram(df, x='Rating', title='Rating Distribution', width=800, height=500, marginal='box')

In [48]:
df['Rating'].describe()

count    8190.000000
mean        4.173321
std         0.536691
min         1.000000
25%         4.000000
50%         4.300000
75%         4.500000
max         5.000000
Name: Rating, dtype: float64

In [49]:
df[df['Rating'] > 3.2]['Rating'].describe()

count    7699.000000
mean        4.268450
std         0.370773
min         3.300000
25%         4.000000
50%         4.300000
75%         4.500000
max         5.000000
Name: Rating, dtype: float64

In [50]:
# Percentage of apps with rating greater than 3.2
print ('Percentage of apps with rating greater than 3.2: ', round(df[df['Rating'] > 3.2]['Rating'].count()/df['Rating'].count()*100, 2), '%')

Percentage of apps with rating greater than 3.2:  94.0 %

In [51]:
# Rating vs Category
df.groupby('Category')['Rating'].median().sort_values(ascending=False)

Category
HEALTH_AND_FITNESS     4.5
BOOKS_AND_REFERENCE    4.5
EVENTS                 4.5
ART_AND_DESIGN         4.4
COMICS                 4.4
EDUCATION              4.4
PERSONALIZATION        4.4
PARENTING              4.4
SPORTS                 4.3
SOCIAL                 4.3
SHOPPING               4.3
PRODUCTIVITY           4.3
PHOTOGRAPHY            4.3
MEDICAL                4.3
AUTO_AND_VEHICLES      4.3
WEATHER                4.3
GAME                   4.3
FOOD_AND_DRINK         4.3
FINANCE                4.3
FAMILY                 4.3
BEAUTY                 4.3
COMMUNICATION          4.2
VIDEO_PLAYERS          4.2
TRAVEL_AND_LOCAL       4.2
TOOLS                  4.2
BUSINESS               4.2
ENTERTAINMENT          4.2
LIBRARIES_AND_DEMO     4.2
NEWS_AND_MAGAZINES     4.2
MAPS_AND_NAVIGATION    4.2
LIFESTYLE              4.2
HOUSE_AND_HOME         4.2
DATING                 4.1
Name: Rating, dtype: float64

In [52]:
# Rating vs Type
df.groupby('Type')['Rating'].median().sort_values(ascending=False)

Type
Paid    4.4
Free    4.3
Name: Rating, dtype: float64

In [53]:
# Rating vs Content Rating
df.groupby('Content Rating')['Rating'].median().sort_values(ascending=False)

Content Rating
Adults only 18+    4.5
Everyone           4.3
Everyone 10+       4.3
Teen               4.3
Mature 17+         4.2
Unrated            4.1
Name: Rating, dtype: float64

In [54]:
# Price
# Remove $ sign and convert to float
df['Price'] = df['Price'].apply(lambda x: x.strip('$')).astype(float)
df.Price.describe()

count    8190.000000
mean        1.038342
std        16.864040
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max       400.000000
Name: Price, dtype: float64

In [55]:
px.histogram(df, x='Price', title='Price Distribution', width=800, height=500, marginal='box')

In [56]:
df.Price.quantile([0.9, 0.92, 0.94, 0.96, 0.98, 1])

0.90      0.00
0.92      0.00
0.94      1.49
0.96      2.99
0.98      4.99
1.00    400.00
Name: Price, dtype: float64

In [57]:
df[df.Price !=0]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
234,TurboScan: scan documents and receipts in PDF,BUSINESS,4.7,11442,6.8M,"100,000+",Paid,4.99,Everyone,Business,"March 25, 2018",1.5.2,4.0 and up
235,Tiny Scanner Pro: PDF Doc Scan,BUSINESS,4.8,10295,39M,"100,000+",Paid,4.99,Everyone,Business,"April 11, 2017",3.4.6,3.0 and up
427,Puffin Browser Pro,COMMUNICATION,4.0,18247,Varies with device,"100,000+",Paid,3.99,Everyone,Communication,"July 5, 2018",7.5.3.20547,4.1 and up
476,"Moco+ - Chat, Meet People",DATING,4.2,1545,Varies with device,"10,000+",Paid,3.99,Mature 17+,Dating,"June 19, 2018",2.6.139,4.1 and up
477,Calculator,DATING,2.6,57,6.2M,"1,000+",Paid,6.99,Everyone,Dating,"October 25, 2017",1.1.6,4.0 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10690,FO Bixby,PERSONALIZATION,5.0,5,861k,100+,Paid,0.99,Everyone,Personalization,"April 25, 2018",0.2,7.0 and up
10697,Mu.F.O.,GAME,5.0,2,16M,1+,Paid,0.99,Everyone,Arcade,"March 3, 2017",1.0,2.3 and up
10760,Fast Tract Diet,HEALTH_AND_FITNESS,4.4,35,2.4M,"1,000+",Paid,7.99,Everyone,Health & Fitness,"August 8, 2018",1.9.3,4.2 and up
10782,Trine 2: Complete Story,GAME,3.8,252,11M,"10,000+",Paid,16.99,Teen,Action,"February 27, 2015",2.22,5.0 and up
10785,"sugar, sugar",FAMILY,4.2,1405,9.5M,"10,000+",Paid,1.20,Everyone,Puzzle,"June 5, 2018",2.7,2.3 and up

In [58]:
# Histogram for Apps with Price > 0

px.histogram(df[df.Price !=0], x='Price', title='Price Distribution', width=800, height=500, marginal='box')

In [59]:
df[df.Type == 'Paid']

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
234,TurboScan: scan documents and receipts in PDF,BUSINESS,4.7,11442,6.8M,"100,000+",Paid,4.99,Everyone,Business,"March 25, 2018",1.5.2,4.0 and up
235,Tiny Scanner Pro: PDF Doc Scan,BUSINESS,4.8,10295,39M,"100,000+",Paid,4.99,Everyone,Business,"April 11, 2017",3.4.6,3.0 and up
427,Puffin Browser Pro,COMMUNICATION,4.0,18247,Varies with device,"100,000+",Paid,3.99,Everyone,Communication,"July 5, 2018",7.5.3.20547,4.1 and up
476,"Moco+ - Chat, Meet People",DATING,4.2,1545,Varies with device,"10,000+",Paid,3.99,Mature 17+,Dating,"June 19, 2018",2.6.139,4.1 and up
477,Calculator,DATING,2.6,57,6.2M,"1,000+",Paid,6.99,Everyone,Dating,"October 25, 2017",1.1.6,4.0 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10690,FO Bixby,PERSONALIZATION,5.0,5,861k,100+,Paid,0.99,Everyone,Personalization,"April 25, 2018",0.2,7.0 and up
10697,Mu.F.O.,GAME,5.0,2,16M,1+,Paid,0.99,Everyone,Arcade,"March 3, 2017",1.0,2.3 and up
10760,Fast Tract Diet,HEALTH_AND_FITNESS,4.4,35,2.4M,"1,000+",Paid,7.99,Everyone,Health & Fitness,"August 8, 2018",1.9.3,4.2 and up
10782,Trine 2: Complete Story,GAME,3.8,252,11M,"10,000+",Paid,16.99,Teen,Action,"February 27, 2015",2.22,5.0 and up
10785,"sugar, sugar",FAMILY,4.2,1405,9.5M,"10,000+",Paid,1.20,Everyone,Puzzle,"June 5, 2018",2.7,2.3 and up

In [60]:
px.histogram(df[df.Type == 'Paid'], x='Price', title='Price Distribution', width=800, height=500, marginal='box')

In [61]:
# Installs
df.Installs.value_counts()

1,000,000+        1414
100,000+          1094
10,000+            986
10,000,000+        937
1,000+             696
5,000,000+         607
500,000+           503
50,000+            456
5,000+             424
100+               303
50,000,000+        202
500+               199
100,000,000+       188
10+                 69
50+                 56
500,000,000+        24
1,000,000,000+      20
5+                   9
1+                   3
Name: Installs, dtype: int64

In [62]:
df['Min Installs'] = df.Installs.apply(lambda x: x.strip('+').replace(',', '')).astype(int)

In [63]:
# Float format
pd.options.display.float_format = '{:,.1f}'.format

In [64]:
df['Min Installs'].describe()

count           8,190.0
mean        9,171,612.9
std        58,271,701.8
min                 1.0
25%            10,000.0
50%           100,000.0
75%         1,000,000.0
max     1,000,000,000.0
Name: Min Installs, dtype: float64

In [65]:
px.histogram(df, x='Min Installs', title='Installs Distribution', width=800, height=500, marginal='box')

In [66]:
df['Installs Group'] = pd.cut(df['Min Installs'], bins=[0, 1000, 10000, 100000, 1000000, 10000000, 100000000, 1000000000], 
                                labels=['0-1k', '1k-10k', '10k-100k', '100k-1M', '1M-10M', '10M-100M', '100M-1B'])

In [67]:
df.groupby('Installs Group')['Installs Group'].count()

Installs Group
0-1k        1335
1k-10k      1410
10k-100k    1550
100k-1M     1917
1M-10M      1544
10M-100M     390
100M-1B       44
Name: Installs Group, dtype: int64

In [68]:
installs_groups = df.groupby('Installs Group')['Installs Group'].count().sort_values(ascending=False)
px.bar(installs_groups, title='Installs Group Count', width=800, height=500, labels={'value':'Count', 'index':'Installs Group'})

In [69]:
df.groupby('Installs Group')['Price'].max().sort_values(ascending=False)

Installs Group
1k-10k     400.0
0-1k       400.0
10k-100k   400.0
100k-1M      7.0
1M-10M       7.0
10M-100M     0.0
100M-1B      0.0
Name: Price, dtype: float64

In [70]:
pd.pivot_table(df, index='Installs Group', values='Price', aggfunc='max')

                Price
Installs Group
0-1k            400.0
1k-10k          400.0
10k-100k        400.0
100k-1M           7.0
1M-10M            7.0
10M-100M          0.0
100M-1B           0.0

In [71]:
pd.pivot_table(df, index='Installs Group', values='Rating', aggfunc='median')

                Rating
Installs Group
0-1k               4.4
1k-10k             4.2
10k-100k           4.2
100k-1M            4.3
1M-10M             4.3
10M-100M           4.4
100M-1B            4.3

In [72]:
# Rating vs Price
px.scatter(df, x='Price', y='Rating', title='Rating vs Price', width=800, height=500)

In [73]:
px.scatter(df[(df['Price'] < 50 ) & (df['Price']> 0)], x='Price', y='Rating', title='Rating vs Price', width=800, height=500)

In [74]:
# Price vs Category
px.scatter(df[(df['Price'] < 50 ) & (df['Price']> 0)], x='Price', y='Category', title='Price vs Category', width=800, height=500)

In [75]:
px.box(df[(df['Price'] < 50 ) & (df['Price']> 0)], y='Price', x='Category', title='Price vs Category', width=900, height=500)

In [76]:
# Type
df.Type.value_counts()

Free    7588
Paid     602
Name: Type, dtype: int64

In [77]:
px.pie(df, names='Type', title='Type Distribution', width=600, height=400)

In [78]:
# Correlation
df.corr()

              Rating  Price  Min Installs
Rating           1.0   -0.0           0.0
Price           -0.0    1.0          -0.0
Min Installs     0.0   -0.0           1.0

In [79]:
# Reviews 
df.Reviews = df.Reviews.astype(int)
df.Reviews.describe()

count        8,190.0
mean       255,435.4
std      1,986,309.5
min              1.0
25%            126.0
50%          3,009.5
75%         43,914.2
max     78,158,306.0
Name: Reviews, dtype: float64

In [80]:
px.histogram(df, x='Reviews', title='Reviews Distribution', width=800, height=500, marginal='box')

In [81]:
# Top 10 apps with most reviews
df.sort_values(by='Reviews', ascending=False)[:10]['App']

2544                                             Facebook
336                                    WhatsApp Messenger
2545                                            Instagram
335              Messenger – Text and Video Chat for Free
1670                                       Clash of Clans
4005              Clean Master- Space Cleaner & Antivirus
1654                                       Subway Surfers
3665                                              YouTube
7536    Security Master - Antivirus, VPN, AppLock, Boo...
1660                                         Clash Royale
Name: App, dtype: object

In [82]:
px.bar(df.nlargest(10, 'Reviews'), x='App', y='Reviews', title='Top 10 apps with most reviews', width=800, height=500)

In [83]:
# Top 10 Free apps with most reviews
df[df['Type'] == 'Free'].nlargest(10, 'Reviews')[['App', 'Reviews']]

                                                    App   Reviews
2544                                           Facebook  78158306
336                                  WhatsApp Messenger  69119316
2545                                          Instagram  66577313
335            Messenger – Text and Video Chat for Free  56642847
1670                                     Clash of Clans  44891723
4005            Clean Master- Space Cleaner & Antivirus  42916526
1654                                     Subway Surfers  27722264
3665                                            YouTube  25655305
7536  Security Master - Antivirus, VPN, AppLock, Boo...  24900999
1660                                       Clash Royale  23133508

In [84]:
# Top 20 Free apps with most rating
df[df['Type'] == 'Free'].nlargest(20, 'Rating')[['App', 'Rating']]

                                             App  Rating
329                 Hojiboy Tojiboyev Life Hacks     5.0
612                American Girls Mobile Numbers     5.0
615                                 Awake Dating     5.0
633                        Spine- The dating app     5.0
636   Girls Live Talk - Free Text and Video Chat     5.0
640                      Online Girls Chat Group     5.0
654              Speeding Joyride & Car Meet App     5.0
1028                            SUMMER SONIC app     5.0
1030                                  Prosperity     5.0
1038                   Mindvalley U Tallinn 2018     5.0
1547                                Eternal life     5.0
2427                                Sway Medical     5.0
2445                              Labs on Demand     5.0
2448  Dermatology Atlas (Colored & Illustrative)     5.0
2450                             Tablet Reminder     5.0
2452                            Galaxies of Hope     5.0
2454                         KBA-EZ Health Guide     5.0
2455                                FoothillsVet     5.0
2457                               PrimeDelivery     5.0
2458                             You're an Anime     5.0

In [85]:
# Top 20 Paid apps with most rating
df[df['Type'] == 'Paid'].nlargest(20, 'Rating')[['App', 'Rating', 'Category', 'Price']]

,App,Rating,Category,Price
2262,Super Hearing Secret Voices Recorder PRO,5.0,MEDICAL,3.0
2271,FHR 5-Tier 2.0,5.0,MEDICAL,3.0
3957,ADS-B Driver,5.0,TOOLS,2.0
4452,P-Home for KLWP,5.0,PERSONALIZATION,1.0
4477,Android P Style Icon Pack,5.0,PERSONALIZATION,1.0
4988,Easy Hotspot Ad Free,5.0,TOOLS,1.0
5237,Hey AJ! It's Saturday!,5.0,BOOKS_AND_REFERENCE,4.0
5246,Hey AJ! It's Bedtime!,5.0,FAMILY,5.0
5260,AJ Gray Dark Icon Pack,5.0,PERSONALIZATION,1.0
5263,AJ Blue Icon Pack,5.0,PERSONALIZATION,1.0
5482,meStudying: AP English Lit,5.0,FAMILY,5.0
5489,AP Art History Flashcards,5.0,FAMILY,30.0
5917,Ra Ga Ba,5.0,GAME,1.5
5966,BC MVA Fines,5.0,BOOKS_AND_REFERENCE,1.8
7100,CA Speakers,5.0,LIFESTYLE,1.0
7204,TI-84 CE Graphing Calculator Manual TI 84,5.0,FAMILY,5.0
7377,CI 174 Gray Icon Pack,5.0,PERSONALIZATION,1.0
7466,211:CK,5.0,GAME,1.0
7477,USMLE Step 2 CK Flashcards,5.0,FAMILY,20.0
8014,Morse Player,5.0,FAMILY,2.0

In [86]:
# Top 10 Paid apps
df.nlargest(10, 'Price')[['App', 'Price']]

                                 App  Price
4367        I'm Rich - Trump Edition  400.0
4197          most expensive app (H)  400.0
4362                      💎 I'm rich  400.0
5351                       I am rich  400.0
5354                  I am Rich Plus  400.0
5356               I Am Rich Premium  400.0
5358                      I am Rich!  400.0
5359              I am rich(premium)  400.0
5362                   I Am Rich Pro  400.0
5364  I am rich (Most expensive app)  400.0

In [1]:
%%writefile googleplaystore.py

import pandas as pd
import streamlit as st

def load_data():
    df = pd.read_csv('googleplaystore.csv')
    return df

def clean_data(df):
    df = df.drop_duplicates(subset='App')
    df = df[df['Rating'] <= 5]
    df = df[df['Reviews'] <= 1000000]

Writing googleplaystore.py