# 📱 Zomato App — Business Context


<p>
Zomato is a global restaurant search, discovery, and food delivery platform that connects users with restaurants across countries.
Through the app and website, customers can browse menus, read reviews, view ratings, compare prices, and place online delivery or table booking requests.
Zomato's data offers valuable insights into customer preferences, pricing trends, popular cuisines, and overall restaurant performance in various markets.
</p>

<hr>

<p>The dataset used in this analysis comes from the <em>Zomato Global Restaurants Data</em> collection and includes the following features:</p>

<table border="1" cellpadding="6" cellspacing="0">
  <thead>
    <tr>
      <th>Feature Name</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    <tr><td><strong>Restaurant ID</strong></td><td>Unique identifier for each restaurant</td></tr>
    <tr><td><strong>Restaurant Name</strong></td><td>Name of the restaurant</td></tr>
    <tr><td><strong>Country Code</strong></td><td>Numeric code representing the country (mapped to country name)</td></tr>
    <tr><td><strong>Country</strong></td><td>Name of the country (after mapping)</td></tr>
    <tr><td><strong>City</strong></td><td>City where the restaurant is located</td></tr>
    <tr><td><strong>Address</strong></td><td>Full street address of the restaurant</td></tr>
    <tr><td><strong>Locality</strong></td><td>Neighborhood or area name</td></tr>
    <tr><td><strong>Locality Verbose</strong></td><td>Detailed location string combining locality and city</td></tr>
    <tr><td><strong>Longitude</strong></td><td>Geographical longitude coordinate</td></tr>
    <tr><td><strong>Latitude</strong></td><td>Geographical latitude coordinate</td></tr>
    <tr><td><strong>Cuisines</strong></td><td>Comma-separated list of cuisines offered by the restaurant</td></tr>
    <tr><td><strong>Average Cost for two</strong></td><td>Estimated average cost for two people dining</td></tr>
    <tr><td><strong>Currency</strong></td><td>Currency in which the average cost is stated</td></tr>
    <tr><td><strong>Has Table booking</strong></td><td>Indicates if table booking is available (Yes/No)</td></tr>
    <tr><td><strong>Has Online delivery</strong></td><td>Indicates if online delivery is available (Yes/No)</td></tr>
    <tr><td><strong>Is delivering now</strong></td><td>Indicates if the restaurant is currently delivering (Yes/No)</td></tr>
    <tr><td><strong>Switch to order menu</strong></td><td>Indicates if an online order menu is available</td></tr>
    <tr><td><strong>Price range</strong></td><td>Price category: 1 (cheapest) to 4 (most expensive)</td></tr>
    <tr><td><strong>Aggregate rating</strong></td><td>Average customer rating on a scale of 0–5</td></tr>
    <tr><td><strong>Rating color</strong></td><td>Color code corresponding to the rating range</td></tr>
    <tr><td><strong>Rating text</strong></td><td>Text description for the rating (e.g., Excellent, Good)</td></tr>
    <tr><td><strong>Votes</strong></td><td>Number of ratings/votes received</td></tr>
  </tbody>
</table>

<hr>

<h3>💼 Business-Oriented Questions — Global Zomato EDA</h3>
<p>The aim is to uncover actionable insights for restaurant owners, food delivery platforms, and market analysts.</p>

<h3>📌 Market &amp; Expansion Strategy</h3>
<ol>
  <li><strong>Which countries and cities have the highest concentration of restaurants?</strong></li>
  <li><strong>What are the most popular cuisines globally, and how do they vary by country?</strong></li>
  <li><strong>Which cuisines achieve the highest average ratings in each region?</strong></li>
  <li><strong>What is the average cost for two in top-performing markets?</strong></li>
  <li><strong>Which countries show a high demand for online delivery vs. dine-in?</strong></li>
</ol>

<h3>📊 Customer Experience &amp; Ratings</h3>
<ol start="6">
  <li><strong>Which factors (cost, online delivery, table booking) correlate most with higher ratings?</strong></li>
  <li><strong>Which countries have the highest customer satisfaction (average rating)?</strong></li>
  <li><strong>Are certain cuisines consistently associated with better ratings?</strong></li>
  <li><strong>Do restaurants with table booking or online delivery have higher average votes?</strong></li>
  <li><strong>What is the relationship between number of votes and rating — do more popular restaurants get better ratings?</strong></li>
</ol>

<hr>

<h3>🧠 Strategic Takeaways</h3>
<p>
Answering these questions will help identify high-potential markets, the most valued cuisines, and operational features that contribute to restaurant success.
The insights can inform market expansion strategies, promotional campaigns, and operational decisions for restaurant owners and food delivery platforms.
</p>

# Inspecting the dataset

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [2]:
df = pd.read_csv('zomato.csv', encoding='latin-1')
df.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229

In [3]:
codes= pd.read_excel('Country-Code.xlsx')
codes.head()

   Country Code    Country
0             1      India
1            14  Australia
2            30     Brazil
3            37     Canada
4            94  Indonesia

In [4]:
df = df.merge(codes, how='left', on='Country Code')
df.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes,Country
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Yes,No,No,No,3,4.8,Dark Green,Excellent,314,Phillipines
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Yes,No,No,No,3,4.5,Dark Green,Excellent,591,Phillipines
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Yes,No,No,No,4,4.4,Green,Very Good,270,Phillipines
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,No,No,No,No,4,4.9,Dark Green,Excellent,365,Phillipines
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Yes,No,No,No,4,4.8,Dark Green,Excellent,229,Phillipines

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9551 entries, 0 to 9550
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Restaurant ID         9551 non-null   int64
 1   Restaurant Name       9551 non-null   object
 2   Country Code          9551 non-null   int64
 3   City                  9551 non-null   object
 4   Address               9551 non-null   object
 5   Locality              9551 non-null   object
 6   Locality Verbose      9551 non-null   object
 7   Longitude             9551 non-null   float64
 8   Latitude              9551 non-null   float64
 9   Cuisines              9542 non-null   object
 10  Average Cost for two  9551 non-null   int64
 11  Currency              9551 non-null   object
 12  Has Table booking     9551 non-null   object
 13  Has Online delivery   9551 non-null   object
 14  Is delivering now     9551 non-null   object
 15  Switch to order menu  9551 non-null   object
 16  Price range           9551 non-null   int64
 17  Aggregate rating      9551 non-null   float64
 18  Rating color          9551 non-null   object
 19  Rating text           9551 non-null   object
 20  Votes                 9551 non-null   int64
 21  Country               9551 non-null   object
dtypes: float64(3), int64(5), object(14)
memory usage: 1.6+ MB

In [6]:
df.duplicated().sum()  # Check for duplicate rows

0

In [7]:
df.isna().sum()  # Check for missing values

Restaurant ID           0
Restaurant Name         0
Country Code            0
City                    0
Address                 0
Locality                0
Locality Verbose        0
Longitude               0
Latitude                0
Cuisines                9
Average Cost for two    0
Currency                0
Has Table booking       0
Has Online delivery     0
Is delivering now       0
Switch to order menu    0
Price range             0
Aggregate rating        0
Rating color            0
Rating text             0
Votes                   0
Country                 0
dtype: int64

In [8]:
# Drop Missing Values 
df.dropna(inplace=True)

In [9]:
# Drop Unnecessary Columns
df.drop(['Restaurant ID','Country Code', 'Address', 'Locality Verbose', 'Locality', 'Longitude', 'Latitude'], axis=1, inplace=True)

In [10]:
# Rearrange Columns
df = df[['Restaurant Name', 'City', 'Country', 'Cuisines', 'Average Cost for two', 'Currency', 'Has Table booking',
         'Has Online delivery', 'Is delivering now', 'Switch to order menu', 'Price range', 'Aggregate rating',
         'Rating color', 'Rating text', 'Votes']]

In [11]:
# from ydata_profiling import ProfileReport
# profile = ProfileReport(df, title="Zomato Restaurants Data Profiling Report", explorative=True)
# profile.to_file("zomato_profiling_report.html")

In [12]:
# Remove duplicate rows (Appeared after ID column was dropped)
df.drop_duplicates(inplace=True)  # Remove duplicate rows

In [13]:
# Drop unnecessary columns
# 'Switch to order menu' has constant values (False)
# 'Rating color' is redundant with 'Rating text'
df.drop(['Switch to order menu', 'Rating color'], axis=1, inplace=True)

In [14]:
# Rename columns for consistency
df.columns = df.columns.str.lower().str.replace(' ', '_')

In [15]:
df.head()

,restaurant_name,city,country,cuisines,average_cost_for_two,currency,has_table_booking,has_online_delivery,is_delivering_now,price_range,aggregate_rating,rating_text,votes
0,Le Petit Souffle,Makati City,Phillipines,"French, Japanese, Desserts",1100,Botswana Pula(P),Yes,No,No,3,4.8,Excellent,314
1,Izakaya Kikufuji,Makati City,Phillipines,Japanese,1200,Botswana Pula(P),Yes,No,No,3,4.5,Excellent,591
2,Heat - Edsa Shangri-La,Mandaluyong City,Phillipines,"Seafood, Asian, Filipino, Indian",4000,Botswana Pula(P),Yes,No,No,4,4.4,Very Good,270
3,Ooma,Mandaluyong City,Phillipines,"Japanese, Sushi",1500,Botswana Pula(P),No,No,No,4,4.9,Excellent,365
4,Sambo Kojin,Mandaluyong City,Phillipines,"Japanese, Korean",1500,Botswana Pula(P),Yes,No,No,4,4.8,Excellent,229

In [16]:
df.describe()

       average_cost_for_two  price_range  aggregate_rating         votes
count           9499.000000  9499.000000       9499.000000   9499.000000
mean            1203.938520     1.807769          2.675039    157.471944
std            16165.119948     0.906272          1.511060    431.049856
min                0.000000     1.000000          0.000000      0.000000
25%              250.000000     1.000000          2.500000      5.000000
50%              400.000000     2.000000          3.200000     31.000000
75%              700.000000     2.000000          3.700000    131.000000
max           800000.000000     4.000000          4.900000  10934.000000

In [17]:
df.describe(include='O')  # Get descriptive statistics for categorical columns

,restaurant_name,city,country,cuisines,currency,has_table_booking,has_online_delivery,is_delivering_now,rating_text
count,9499,9499,9499,9499,9499,9499,9499,9499,9499
unique,7437,140,15,1825,12,2,2,2,6
top,Domino's Pizza,New Delhi,India,North Indian,Indian Rupees(Rs.),No,No,No,Average
freq,78,5450,8609,935,8609,8341,7054,9465,3727

In [18]:
df['price_range'].value_counts()  # Check unique values in 'Price range'

price_range
1    4403
2    3105
3    1405
4     586
Name: count, dtype: int64

In [19]:
df['price_range'] = df['price_range'].astype('category')

In [20]:
# Numercial columns 
num_cols = df.select_dtypes(include=[np.number]).columns.tolist()

# Categorical columns
cat_cols = df.select_dtypes(exclude=[np.number]).columns.tolist()

In [21]:
df['average_cost_for_two'].quantile([0.25, 0.5, 0.75, 0.9, 0.95, 0.995, 0.999])

0.250       250.0
0.500       400.0
0.750       700.0
0.900      1200.0
0.950      1700.0
0.995      4500.0
0.999    200000.0
Name: average_cost_for_two, dtype: float64

In [22]:
df = df[df['average_cost_for_two'] > 0]  # Remove rows with zero cost
df = df[df['average_cost_for_two'] < df['average_cost_for_two'].quantile(0.995) ]  # Remove outliers

In [23]:
df.shape

(9425, 13)

# Univariate Analysis

In [24]:
def explore_num_col(df, col):
    fig = px.histogram(df, x=col, marginal='box', title=f'Distribution of {col}', width=900)
    fig.update_layout(xaxis_title=col, yaxis_title='Count')
    fig.show()

def explore_cat_col(df, col):
    fig = px.histogram(df, x=col, title=f'Distribution of {col}', category_orders={col: df[col].value_counts().index}, width=900)
    fig.update_layout(xaxis_title=col, yaxis_title='Count')
    fig.show()

In [25]:
for col in num_cols:
    explore_num_col(df, col)

In [26]:
for col in cat_cols:
    explore_cat_col(df, col)

* Insights 
  * Most Numerical Columns are skewed to the right
  * Some restaurants having very high costs (Average Cost for two)
  * Many restaurants have zero aggregate rating
  * A few restaurants have very high number of votes
  * Most restaurants in India
  * Most restaurants have online delivery and table booking options
  * Most restaurants have a price range of 1 or 2
  * Almost all restaurants have IS delivering now as 'No'
  * Excellent and Poor ratings are the least common while Average is the most common and Some restaurants have no ratings at all

# 📌 Market & Expansion Strategy

## Which countries and cities have the highest concentration of restaurants?

In [27]:
df.columns

Index(['restaurant_name', 'city', 'country', 'cuisines',
       'average_cost_for_two', 'currency', 'has_table_booking',
       'has_online_delivery', 'is_delivering_now', 'price_range',
       'aggregate_rating', 'rating_text', 'votes'],
      dtype='object')

In [30]:
df.country.value_counts()

country
India             8564
United States      419
United Kingdom      80
Brazil              60
UAE                 60
South Africa        60
New Zealand         40
Turkey              34
Australia           24
Phillipines         21
Singapore           20
Qatar               20
Sri Lanka           19
Canada               4
Name: count, dtype: int64

In [32]:
df.city.value_counts()

city
New Delhi        5416
Gurgaon          1112
Noida            1065
Faridabad         250
Ghaziabad          25
                 ...
Mc Millan           1
Mayfield            1
Macedon             1
Lorn                1
Victor Harbor       1
Name: count, Length: 136, dtype: int64

In [33]:
print(f'Top Country: {df["country"].value_counts().idxmax()}')
print(f'Top City: {df["city"].value_counts().idxmax()}')

Top Country: India
Top City: New Delhi

In [60]:
# Top 3 countries with most restaurants
top_countries = df['country'].value_counts().nlargest(3)
top_countries

country
India             8564
United States      419
United Kingdom      80
Name: count, dtype: int64

In [61]:
other_countries_count = df.country.size - top_countries.sum() 
other_countries_count

362

In [62]:
top_countries.loc['Others'] = other_countries_count
top_countries

country
India             8564
United States      419
United Kingdom      80
Others             362
Name: count, dtype: int64

In [63]:
# Top 3 cities with most restaurants
top_cities = df['city'].value_counts().nlargest(3)
other_cities_count = df.city.size - top_cities.sum()
top_cities.loc['Others'] = other_cities_count
top_cities

city
New Delhi    5416
Gurgaon      1112
Noida        1065
Others       1832
Name: count, dtype: int64

In [66]:
px.pie(top_countries, values=top_countries.values, names=top_countries.index, width=900, title='Top countries with most restaurants')

In [67]:
px.pie(top_cities, values=top_cities.values, names=top_cities.index, title='Top Cities with Most Restaurants', width=900)

## What are the most popular cuisines globally, and how do they vary by country?

In [69]:
df.cuisines.value_counts().nlargest(10)

cuisines
North Indian                      934
North Indian, Chinese             510
Fast Food                         353
Chinese                           348
North Indian, Mughlai             334
Cafe                              282
Bakery                            218
North Indian, Mughlai, Chinese    197
Bakery, Desserts                  167
Street Food                       148
Name: count, dtype: int64

In [89]:
popular_cuisines = (
    df.groupby('country')['cuisines']
      .apply(lambda x: x.value_counts().head(1))  
      .sort_values(ascending=False).reset_index()
)

popular_cuisines.columns = ['country', 'most_popular_cuisine', 'count']

popular_cuisines

           country most_popular_cuisine  count
0            India         North Indian    934
1    United States              Mexican     22
2           Brazil            Brazilian      8
3   United Kingdom              Italian      7
4           Turkey                 Cafe      6
5      New Zealand                 Cafe      5
6            Qatar               Indian      5
7              UAE               Indian      5
8      Phillipines             Filipino      3
9     South Africa              Mexican      3
10       Australia                 Cafe      2
11       Singapore               French      2
12          Canada      Japanese, Sushi      1
13       Sri Lanka              Chinese      1

In [90]:
px.bar(df.cuisines.value_counts().nlargest(10),
       x=df.cuisines.value_counts().nlargest(10).index,
       y=df.cuisines.value_counts().nlargest(10).values,
       width=900, title='Top 10 Cuisines')

## Which cuisines achieve the highest average ratings?

In [98]:
df.groupby('cuisines')['aggregate_rating'].agg(['size', 'median']).sort_values(by='median', ascending=False).head(10)

                                       size  median
cuisines
Continental, Indian                       1     4.9
Italian, Deli                             1     4.9
European, Contemporary                    1     4.9
American, Sandwich, Tea                   1     4.9
European, Mediterranean, North Indian     3     4.9
Mughlai, Lucknowi                         1     4.9
Burger, Bar Food, Steak                   1     4.9
Hawaiian, Seafood                         1     4.9
BBQ, Breakfast, Southern                  1     4.9
Mexican, American, Healthy Food           1     4.9

In [99]:
df.groupby('cuisines')['aggregate_rating'].agg(['size', 'median']).sort_values(by='size', ascending=False).head(10)

                                size  median
cuisines
North Indian                     934     2.6
North Indian, Chinese            510     2.9
Fast Food                        353     3.0
Chinese                          348     2.8
North Indian, Mughlai            334     3.2
Cafe                             282     3.3
Bakery                           218     3.0
North Indian, Mughlai, Chinese   197     3.0
Bakery, Desserts                 167     3.1
Street Food                      148     3.1

* Cuisines with the highest ratings are not necessarily the most popular.
* The most popular cuisines globally have the low ratings.

In [102]:
df.groupby('cuisines')['votes'].agg(['size', 'median']).sort_values(by='size', ascending=False).head(10)

                                size  median
cuisines
North Indian                     934     4.0
North Indian, Chinese            510    20.5
Fast Food                        353    10.0
Chinese                          348    10.0
North Indian, Mughlai            334    45.5
Cafe                             282    39.0
Bakery                           218     6.0
North Indian, Mughlai, Chinese   197    37.0
Bakery, Desserts                 167    10.0
Street Food                      148    12.0

## What are the most popular restaurants?

In [140]:
popular_restaurants = df.groupby('restaurant_name').size().nlargest(10)
popular_restaurants

restaurant_name
Domino's Pizza      78
Cafe Coffee Day     71
Subway              63
Green Chick Chop    48
McDonald's          48
Keventers           32
Pizza Hut           30
Giani               29
Barbeque Nation     26
Baskin Robbins      24
dtype: int64

In [141]:
px.bar(popular_restaurants,
       x=popular_restaurants.index,
       y=popular_restaurants.values,
       width=900, title='Top 10 Restaurants')

## Which restaurants have the highest number of votes?

In [126]:
top_restaurants = df.nlargest(10, 'votes')[['restaurant_name', 'country', 'city',  'cuisines', 'votes']].reset_index(drop=True)
top_restaurants

,restaurant_name,country,city,cuisines,votes
0,Toit,India,Bangalore,"Italian, American, Pizza",10934
1,Truffles,India,Bangalore,"American, Burger, Cafe",9667
2,Hauz Khas Social,India,New Delhi,"Continental, American, Asian, North Indian",7931
3,Peter Cat,India,Kolkata,"Continental, North Indian",7574
4,AB's - Absolute Barbecues,India,Bangalore,"European, Mediterranean, North Indian",6907
5,Barbeque Nation,India,Kolkata,"North Indian, Chinese",5966
6,Big Brewsky,India,Bangalore,"Finger Food, North Indian, Italian, Continenta...",5705
7,AB's - Absolute Barbecues,India,Hyderabad,"European, Mediterranean, North Indian",5434
8,The Black Pearl,India,Bangalore,"North Indian, European, Mediterranean",5385
9,BarBQ,India,Kolkata,"Chinese, North Indian",5288

In [127]:
top_restaurants_ordered = top_restaurants.groupby('restaurant_name')['votes'].sum().sort_values(ascending=False).index.to_list()
top_restaurants_ordered

["AB's - Absolute Barbecues",
 'Toit',
 'Truffles',
 'Hauz Khas Social',
 'Peter Cat',
 'Barbeque Nation',
 'Big Brewsky',
 'The Black Pearl',
 'BarBQ']

In [133]:
px.bar(top_restaurants, x='restaurant_name', y='votes', color='city',
       title='Top 10 Restaurants by Votes', width=900, height=600, color_discrete_sequence=px.colors.qualitative.Dark2,
       category_orders={'restaurant_name': top_restaurants_ordered}
)

In [ ]:
cuisines = df['Cuisines'].dropna().str.split(',').explode().str.strip()
top_cuisines = cuisines.value_counts().head(10)
plt.figure(figsize=(10,6))
sns.barplot(x=top_cuisines.values, y=top_cuisines.index, palette="crest")
plt.title("Top 10 Most Popular Cuisines")
plt.xlabel("Number of Restaurants")
plt.show()